services:
  edgedb-postgres:
    image: postgres:16
    container_name: edgedb-postgres
    ports: [ '5432:5432' ]
    healthcheck:
      test: pg_isready --username=postgres --dbname=postgres
      interval: 1s
      timeout: 1s
      start_period: 1s
      retries: 30
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  edgedb:
    image: edgedb/edgedb:5.6
    container_name: edgedb
    ports: [ '5656:5656' ]
    healthcheck:
      test: curl -sSf http://localhost:5656/server/status/ready
      interval: 1s
      timeout: 1s
      start_period: 5s
      retries: 30
    environment:
      EDGEDB_SERVER_BACKEND_DSN: 'postgresql://edgedb:edgedb@edgedb-postgres:5432/edgedb'
      EDGEDB_SERVER_TLS_CERT_MODE: 'generate_self_signed'
      EDGEDB_SERVER_PASSWORD: 'edgedb'